version: '3.7'
services:
  api:
    build: ./backend
    tty: true
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: infomap
      POSTGRES_PASSWORD: infomap
      POSTGRES_DB: infomap
    ports:
      - 5432:5432
