version: '3.7'
services:
  api:
    build: ./backend
    tty: true
    volumes:
      - ./backend:/go/src/github.com/wasuken/infomap.local
    ports:
      - "8081:8080"
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: infomap
      POSTGRES_PASSWORD: infomap
      POSTGRES_DB: infomap
    ports:
      - 5432:5432
  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: ng9
    ports:
      - "7000:8080"
